# Generated by Django 2.2.6 on 2019-10-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='code',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(through='Hackathon.GroupStudent', to='Hackathon.Student', verbose_name='list of students'),
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Hackathon.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Hackathon.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='fruit',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(through='Hackathon.GroupStudent', to='Hackathon.Group', verbose_name='list of groups'),
        ),
        migrations.AlterUniqueTogether(
            name='groupstudent',
            unique_together={('group', 'student')},
        ),
        migrations.AlterModelTable(
            name='group',
            table=None,
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
